// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class Base64Image
    {
        /// <summary>
        /// Initializes a new instance of the Base64Image class.
        /// </summary>
        public Base64Image() { }

        /// <summary>
        /// Initializes a new instance of the Base64Image class.
        /// </summary>
        public Base64Image(string base64 = default(string))
        {
            Base64 = base64;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "base64")]
        public string Base64 { get; set; }

    }
}
