// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class HtmlContentModel
    {
        /// <summary>
        /// Initializes a new instance of the HtmlContentModel class.
        /// </summary>
        public HtmlContentModel() { }

        /// <summary>
        /// Initializes a new instance of the HtmlContentModel class.
        /// </summary>
        public HtmlContentModel(string htmlContent)
        {
            HtmlContent = htmlContent;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "htmlContent")]
        public string HtmlContent { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (HtmlContent == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "HtmlContent");
            }
        }
    }
}
