// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class InvitationResult
    {
        /// <summary>
        /// Initializes a new instance of the InvitationResult class.
        /// </summary>
        public InvitationResult() { }

        /// <summary>
        /// Initializes a new instance of the InvitationResult class.
        /// </summary>
        public InvitationResult(System.Collections.Generic.IList<string> failedInvitations = default(System.Collections.Generic.IList<string>), System.Collections.Generic.IList<string> existingUsers = default(System.Collections.Generic.IList<string>))
        {
            FailedInvitations = failedInvitations;
            ExistingUsers = existingUsers;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "failedInvitations")]
        public System.Collections.Generic.IList<string> FailedInvitations { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "existingUsers")]
        public System.Collections.Generic.IList<string> ExistingUsers { get; set; }

    }
}
