// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class LayerRelationRule
    {
        /// <summary>
        /// Initializes a new instance of the LayerRelationRule class.
        /// </summary>
        public LayerRelationRule() { }

        /// <summary>
        /// Initializes a new instance of the LayerRelationRule class.
        /// </summary>
        public LayerRelationRule(int sourceLayerId, int targetLayerId, Layer sourceLayer = default(Layer), Layer targetLayer = default(Layer), int? id = default(int?), string title = default(string), string description = default(string), string arrowStyle = default(string), string color = default(string))
        {
            SourceLayerId = sourceLayerId;
            SourceLayer = sourceLayer;
            TargetLayerId = targetLayerId;
            TargetLayer = targetLayer;
            Id = id;
            Title = title;
            Description = description;
            ArrowStyle = arrowStyle;
            Color = color;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "sourceLayerId")]
        public int SourceLayerId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "sourceLayer")]
        public Layer SourceLayer { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "targetLayerId")]
        public int TargetLayerId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "targetLayer")]
        public Layer TargetLayer { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "arrowStyle")]
        public string ArrowStyle { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "color")]
        public string Color { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
