// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class PagedResultUserResult
    {
        /// <summary>
        /// Initializes a new instance of the PagedResultUserResult class.
        /// </summary>
        public PagedResultUserResult() { }

        /// <summary>
        /// Initializes a new instance of the PagedResultUserResult class.
        /// </summary>
        public PagedResultUserResult(System.Collections.Generic.IList<UserResult> items = default(System.Collections.Generic.IList<UserResult>), Pagination metadata = default(Pagination))
        {
            Items = items;
            Metadata = metadata;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "items")]
        public System.Collections.Generic.IList<UserResult> Items { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "metadata")]
        public Pagination Metadata { get; set; }

    }
}
