// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class StudentDetailsResult
    {
        /// <summary>
        /// Initializes a new instance of the StudentDetailsResult class.
        /// </summary>
        public StudentDetailsResult() { }

        /// <summary>
        /// Initializes a new instance of the StudentDetailsResult class.
        /// </summary>
        public StudentDetailsResult(string discipline = default(string), string currentDegree = default(string), int? currentSemester = default(int?))
        {
            Discipline = discipline;
            CurrentDegree = currentDegree;
            CurrentSemester = currentSemester;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "discipline")]
        public string Discipline { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "currentDegree")]
        public string CurrentDegree { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "currentSemester")]
        public int? CurrentSemester { get; set; }

    }
}
