// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class StudentFormModel
    {
        /// <summary>
        /// Initializes a new instance of the StudentFormModel class.
        /// </summary>
        public StudentFormModel() { }

        /// <summary>
        /// Initializes a new instance of the StudentFormModel class.
        /// </summary>
        public StudentFormModel(string discipline, string currentDegree, int currentSemester)
        {
            Discipline = discipline;
            CurrentDegree = currentDegree;
            CurrentSemester = currentSemester;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "discipline")]
        public string Discipline { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "currentDegree")]
        public string CurrentDegree { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "currentSemester")]
        public int CurrentSemester { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Discipline == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Discipline");
            }
            if (CurrentDegree == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "CurrentDegree");
            }
        }
    }
}
