// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class TagFormModel
    {
        /// <summary>
        /// Initializes a new instance of the TagFormModel class.
        /// </summary>
        public TagFormModel() { }

        /// <summary>
        /// Initializes a new instance of the TagFormModel class.
        /// </summary>
        public TagFormModel(string name = default(string), string shortName = default(string), string layer = default(string), string description = default(string), string style = default(string))
        {
            Name = name;
            ShortName = shortName;
            Layer = layer;
            Description = description;
            Style = style;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "shortName")]
        public string ShortName { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "layer")]
        public string Layer { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "style")]
        public string Style { get; set; }

    }
}
