// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class TagFrequency
    {
        /// <summary>
        /// Initializes a new instance of the TagFrequency class.
        /// </summary>
        public TagFrequency() { }

        /// <summary>
        /// Initializes a new instance of the TagFrequency class.
        /// </summary>
        public TagFrequency(string value = default(string), int? count = default(int?), int? tagId = default(int?))
        {
            Value = value;
            Count = count;
            TagId = tagId;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "tagId")]
        public int? TagId { get; set; }

    }
}
