// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class TagResult
    {
        /// <summary>
        /// Initializes a new instance of the TagResult class.
        /// </summary>
        public TagResult() { }

        /// <summary>
        /// Initializes a new instance of the TagResult class.
        /// </summary>
        public TagResult(int? tagId = default(int?), string name = default(string), string shortName = default(string), string layer = default(string), string style = default(string), string description = default(string), bool? isDeleted = default(bool?), int? usageCount = default(int?))
        {
            TagId = tagId;
            Name = name;
            ShortName = shortName;
            Layer = layer;
            Style = style;
            Description = description;
            IsDeleted = isDeleted;
            UsageCount = usageCount;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "tagId")]
        public int? TagId { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "shortName")]
        public string ShortName { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "layer")]
        public string Layer { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "style")]
        public string Style { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "usageCount")]
        public int? UsageCount { get; private set; }

    }
}
