// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class TopicReviewResult
    {
        /// <summary>
        /// Initializes a new instance of the TopicReviewResult class.
        /// </summary>
        public TopicReviewResult() { }

        /// <summary>
        /// Initializes a new instance of the TopicReviewResult class.
        /// </summary>
        public TopicReviewResult(TopicReviewStatus status = default(TopicReviewStatus), System.DateTime? timeStamp = default(System.DateTime?), UserResult reviewer = default(UserResult))
        {
            Status = status;
            TimeStamp = timeStamp;
            Reviewer = reviewer;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "status")]
        public TopicReviewStatus Status { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "timeStamp")]
        public System.DateTime? TimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "reviewer")]
        public UserResult Reviewer { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.Status != null)
            {
                this.Status.Validate();
            }
        }
    }
}
