// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class TopicAttachmentResult
    {
        /// <summary>
        /// Initializes a new instance of the TopicAttachmentResult class.
        /// </summary>
        public TopicAttachmentResult() { }

        /// <summary>
        /// Initializes a new instance of the TopicAttachmentResult class.
        /// </summary>
        public TopicAttachmentResult(int? id = default(int?), string title = default(string), Metadata metadata = default(Metadata), string type = default(string), UserResult user = default(UserResult), System.DateTime? createdAt = default(System.DateTime?))
        {
            Id = id;
            Title = title;
            Metadata = metadata;
            Type = type;
            User = user;
            CreatedAt = createdAt;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "metadata")]
        public Metadata Metadata { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "user")]
        public UserResult User { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.Metadata != null)
            {
                this.Metadata.Validate();
            }
        }
    }
}
