// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class TopicResult
    {
        /// <summary>
        /// Initializes a new instance of the TopicResult class.
        /// </summary>
        public TopicResult() { }

        /// <summary>
        /// Initializes a new instance of the TopicResult class.
        /// </summary>
        public TopicResult(int? id = default(int?), string title = default(string), string status = default(string), System.DateTime? deadline = default(System.DateTime?), string description = default(string), string requirements = default(string), UserResult createdBy = default(UserResult), System.DateTime? createdAt = default(System.DateTime?), UserResult updatedBy = default(UserResult), System.DateTime? updatedAt = default(System.DateTime?))
        {
            Id = id;
            Title = title;
            Status = status;
            Deadline = deadline;
            Description = description;
            Requirements = requirements;
            CreatedBy = createdBy;
            CreatedAt = createdAt;
            UpdatedBy = updatedBy;
            UpdatedAt = updatedAt;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "deadline")]
        public System.DateTime? Deadline { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "requirements")]
        public string Requirements { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "createdBy")]
        public UserResult CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "updatedBy")]
        public UserResult UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

    }
}
