// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class UserResult
    {
        /// <summary>
        /// Initializes a new instance of the UserResult class.
        /// </summary>
        public UserResult() { }

        /// <summary>
        /// Initializes a new instance of the UserResult class.
        /// </summary>
        public UserResult(string identity = default(string), string email = default(string), string firstName = default(string), string lastName = default(string), string role = default(string), StudentDetailsResult studentDetails = default(StudentDetailsResult), string fullName = default(string))
        {
            Identity = identity;
            Email = email;
            FirstName = firstName;
            LastName = lastName;
            Role = role;
            StudentDetails = studentDetails;
            FullName = fullName;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "identity")]
        public string Identity { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "role")]
        public string Role { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "studentDetails")]
        public StudentDetailsResult StudentDetails { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fullName")]
        public string FullName { get; private set; }

    }
}
