// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.FeatureToggle.Clients.Models
{
    using System.Linq;

    public partial class VirtualFileResult
    {
        /// <summary>
        /// Initializes a new instance of the VirtualFileResult class.
        /// </summary>
        public VirtualFileResult() { }

        /// <summary>
        /// Initializes a new instance of the VirtualFileResult class.
        /// </summary>
        public VirtualFileResult(string fileName = default(string), object fileProvider = default(object), string contentType = default(string), string fileDownloadName = default(string))
        {
            FileName = fileName;
            FileProvider = fileProvider;
            ContentType = contentType;
            FileDownloadName = fileDownloadName;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fileProvider")]
        public object FileProvider { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "contentType")]
        public string ContentType { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fileDownloadName")]
        public string FileDownloadName { get; set; }

    }
}
